# Generated by Django 4.2.7 on 2023-12-06 04:09

from django.db import migrations

def create_data(apps, schema_editor):
    Contact = apps.get_model('opensmsapp', 'Contact')
    Contact(name="Joe Silver", email="joe@email.com", phone="14082037554").save()


class Migration(migrations.Migration):

    dependencies = [
        ('opensmsapp', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(create_data),
    ]
